### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by trondtynnol** [giellalt/lang-nno-x-ext-apertium#1]
I have problems compiling this at least since the restructuring. It halts on `No rule to make target 'ext-Apertium-spa/apertium-spa.spa.dix', needed by 'lexicon.lexc'. ` I also have the same problem with the Spanish analyzer imported from Apertium.  A more complete log is here:
```
make[3]: Entering directory '/home/trond/gt/github/giellalt/lang-spa-x-ext-apertium/src/fst/morphology'
Makefile:1361: warning: overriding recipe for target 'lexicon.hfst'
Makefile:1292: warning: ignoring old recipe for target 'lexicon.hfst'
Making all in .
make[4]: Entering directory '/home/trond/gt/github/giellalt/lang-spa-x-ext-apertium/src/fst/morphology'
Makefile:1361: warning: overriding recipe for target 'lexicon.hfst'
Makefile:1292: warning: ignoring old recipe for target 'lexicon.hfst'
make[4]: *** No rule to make target 'ext-Apertium-spa/apertium-spa.spa.dix', needed by 'lexicon.lexc'.  Stop.
make[4]: Leaving directory '/home/trond/gt/github/giellalt/lang-spa-x-ext-apertium/src/fst/morphology'
make[3]: *** [Makefile:967: all-recursive] Error 1
make[3]: Leaving directory '/home/trond/gt/github/giellalt/lang-spa-x-ext-apertium/src/fst/morphology'
```

**Comment by trondtynnol** [comment]
@flammie does this have anything to do with the restructuring, maybe?

**Comment by trondtynnol** [comment]
I am still having compiling problems, but now from another error, `No rule to make target '.hfst', needed by '.generated/lexicon-sigma.txt'.`:
```
make[4]: Entering directory '/home/trond/gt/github/giellalt/lang-nno-x-ext-apertium/src/fst/morphology'
Makefile:1356: warning: overriding recipe for target 'lexicon.hfst'
Makefile:1289: warning: ignoring old recipe for target 'lexicon.hfst'
  GEN      .generated/.stamp
  HLEXC    .generated/lexicon.hfst
  HREVERSE .generated/lexicon.rev.hfst
make .generated/.stamp
make[5]: Entering directory '/home/trond/gt/github/giellalt/lang-nno-x-ext-apertium/src/fst/morphology'
Makefile:1356: warning: overriding recipe for target 'lexicon.hfst'
Makefile:1289: warning: ignoring old recipe for target 'lexicon.hfst'
make[5]: '.generated/.stamp' is up to date.
make[5]: Leaving directory '/home/trond/gt/github/giellalt/lang-nno-x-ext-apertium/src/fst/morphology'
  CP       .generated/url.tmp.lexc
  HLEXC    .generated/url.hfst
  HTXT2FST .generated/lexicon.tmp.hfst
make[4]: *** No rule to make target '.hfst', needed by '.generated/lexicon-sigma.txt'.  Stop.
make[4]: Leaving directory '/home/trond/gt/github/giellalt/lang-nno-x-ext-apertium/src/fst/morphology'
```

**Comment by flammie** [comment]
It works on my machine now :-D

is this on mac? The compilation of lexicon-sigma from clean should just go like this:

```console
$ make V=1 .generated/lexicon-sigma.txt
Makefile:1357: Warnung: Das Rezept für das Ziel „lexicon.hfst“ wird überschrieben
Makefile:1290: Warnung: Das alte Rezept für das Ziel „lexicon.hfst“ wird ignoriert
/usr/bin/mkdir -p `dirname .generated/.stamp`
touch .generated/.stamp
gunzip --stdout ext-Apertium-nno/nno.automorf.att.gz \
	| sed -e "s/ /\'@_SPACE_@\'/g" \
	| /usr/bin/hfst-txt2fst -v --format=foma --epsilon=ε \
	| /usr/bin/hfst-invert -v \
	-o .generated/lexicon.tmp.hfst
Reading from <stdin>, writing to <stdout>
Using foma as output handler
Reading transducer table...
Reading from <stdin>, writing to .generated/lexicon.tmp.hfst
Reading transducer table 2...
Inverting text(<stdin>)...
Inverting text(<stdin>)...2
Reading transducer table 3...
Inverting text(<stdin>)...3
cp .generated/lexicon.tmp.hfst lexicon.tmp.hfst
/usr/bin/hfst-summarize -v 2>/dev/null lexicon.tmp.hfst \
	| grep -A1 '^sigma set' \
	| grep -v '^sigma set' \
	| sed 's/, /\\\\\\/g' \
	| perl -pe 's/\\\\\\/\n/g' \
	| grep -v '^$' \
	| egrep -v '(@_EPSILON_SYMBOL_@|@_IDENTITY_SYMBOL_@|@_UNKNOWN_SYMBOL_@)' \
	> .generated/lexicon-sigma.txt
```

I added few extra things to makefile that might fix it...

**Comment by trondtynnol** [comment]
This was on Linux (Pop_OS), but your hacks seem to have fixed the problems there as well. Thanks!

Would you do the same fixes to the other Apertium-imported repositories like [lang-spa-x-ext-apertium](https://github.com/giellalt/lang-spa-x-ext-apertium)?

**Comment by snomos** [comment]
Please note that external sources should be included using `git subtree`, cf https://giellalt.github.io/infra/GutUsageExamples.html#task-15-add-external-repo and https://gist.github.com/SKempin/b7857a6ff6bddb05717cc17a44091202

`git subtree` makes the external code part of the local source tree (as opposed to `git submodule`) and thus makes builds easier, while at the same time allowing both regular updates of and even pushes to the external source.

What is not yet done is to add a simple shell script for updating the external source – the `git subtree` command can be a bit intimidating for casual users wanting to update it.

**Comment by snomos** [comment]
See also https://stackoverflow.com/questions/49028258/git-remove-subtree-or-change-directory-of-subtree

**Comment by snomos** [comment]
`git subtree pull` did not work, I had to delete the subtree and add it as a new git subtree  to make subtree pulls work properly again.

**Comment by snomos** [comment]
> What is not yet done is to add a simple shell script for updating the external source – the `git subtree` command can be a bit intimidating for casual users wanting to update it.

I forgot that I have added a 'make update' in the top-level makefile of the relevant repos, so everything is fine re this.

What needs to be done is move the sources of the other subtree dirs after the dir reorg. The list of all external source repos is:

- [x] `lang-nno-x-ext-apertium`
- [x] `lang-quc-x-ext-apertium`
- [x] `lang-spa-x-ext-apertium`
- [x] `lang-tur-x-ext-trmorph`
- [x] `lang-vot-x-ext-kkankain`
